## Define stages
stages:
  - database
  - backend
  - frontend

# ## Database
# database:
#   stage: database
#   trigger:
#     include:
#       - local: "database/.gitlab-ci.yml"
#     strategy: depend
#   rules:
#     - changes:
#       - database/**/*

## Backend
backend:
  stage: backend
  trigger:
    include:
      - local: "backend/.gitlab-ci.yml"
    strategy: depend
  # rules:
  #   - changes:
  #     - backend/**/*

# ## Frontend
# frontend:
#   stage: frontend
#   trigger:
#     include:
#       - local: "frontend/.gitlab-ci.yml"
#     strategy: depend
#   rules:
#     - changes:
#       - frontend/**/*
